Size:
    height: 10
    width: 80
    
Behaviour:
    allowEditSL: True

Font:
    font: courier 12

Chronometer:
    status: show
    #possible values: show / hide

Text:
    file: original-TA.txt
    
Actions:
    file: actions.txt
    
Languages:
    source: eng
    target: spa
    
Definition:
    symbols: "! @ # $ % ^ & ( ) _ { } [ ] ' ? ¿ ! ¡ < >"
    punctuation: ", : ; ."
    nameuserdef1: mathematical
    userdef1: "+ - * / =" 
    nameuserdef2: None
    userdef2: None
    nameuserdef3: None
    userdef3: None
